# Generated by Django 5.1.1 on 2024-10-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=500)),
                ('pdesc', models.CharField(max_length=1000)),
                ('pconstraint', models.CharField(max_length=100)),
                ('plevel', models.CharField(default='', max_length=100)),
                ('pyoutube', models.CharField(default='', max_length=200)),
                ('particle', models.CharField(default='', max_length=200)),
                ('pinput', models.CharField(default='', max_length=200)),
                ('poutput', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Snippets',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('snippets', models.TextField()),
                ('language', models.CharField(default='', max_length=20)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apicode.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tinput', models.CharField(max_length=200)),
                ('toutput', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicode.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicode.problems')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicode.user')),
            ],
        ),
    ]
