# Generated by Django 5.1.1 on 2024-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippets',
            name='language',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
