# Generated by Django 5.1.1 on 2024-10-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicode', '0002_alter_snippets_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
