# Generated by Django 5.1.1 on 2024-10-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicode', '0003_solved_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='lang',
            field=models.CharField(default='', max_length=20),
        ),
    ]
