# Generated by Django 5.1.1 on 2024-10-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicode', '0004_solved_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
